--
-- Name: tb_actor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_actor (
    id bigint NOT NULL,
    birthday date,
    nacionality character varying(255),
    name character varying(255),
    movie_id bigint
);


--
-- Name: tb_actor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_actor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_actor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_category (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_comment (
    id bigint NOT NULL,
    moment timestamp(6) with time zone,
    text character varying(255),
    movie_id bigint,
    user_id bigint,
    comment_id bigint
);


--
-- Name: tb_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_movie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_movie (
    id bigint NOT NULL,
    description character varying(255),
    release_date date,
    review_rating double precision,
    title character varying(255),
    category_id bigint
);


--
-- Name: tb_movie_actor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_movie_actor (
    movie_id bigint NOT NULL,
    actor_id bigint NOT NULL
);


--
-- Name: tb_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255)
);


--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_actor tb_actor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_actor
    ADD CONSTRAINT tb_actor_pkey PRIMARY KEY (id);


--
-- Name: tb_category tb_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_category
    ADD CONSTRAINT tb_category_pkey PRIMARY KEY (id);


--
-- Name: tb_comment tb_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_comment
    ADD CONSTRAINT tb_comment_pkey PRIMARY KEY (id);


--
-- Name: tb_movie_actor tb_movie_actor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_movie_actor
    ADD CONSTRAINT tb_movie_actor_pkey PRIMARY KEY (movie_id, actor_id);


--
-- Name: tb_movie tb_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_movie
    ADD CONSTRAINT tb_movie_pkey PRIMARY KEY (id);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: tb_comment fk3kuip06uwa6ivpt6cffnhmcec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_comment
    ADD CONSTRAINT fk3kuip06uwa6ivpt6cffnhmcec FOREIGN KEY (comment_id) REFERENCES public.tb_user(id);


--
-- Name: tb_comment fk45c1cuqlljd60ihc9j0962ekq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_comment
    ADD CONSTRAINT fk45c1cuqlljd60ihc9j0962ekq FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- Name: tb_comment fki79tsew4u3uuilsvu6363c5ve; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_comment
    ADD CONSTRAINT fki79tsew4u3uuilsvu6363c5ve FOREIGN KEY (movie_id) REFERENCES public.tb_movie(id);


--
-- Name: tb_movie_actor fkkc11oso89pvbyrwpg265bmj9v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_movie_actor
    ADD CONSTRAINT fkkc11oso89pvbyrwpg265bmj9v FOREIGN KEY (movie_id) REFERENCES public.tb_movie(id);


--
-- Name: tb_movie_actor fknaiva749sdfsiyo4xsj3xajqi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_movie_actor
    ADD CONSTRAINT fknaiva749sdfsiyo4xsj3xajqi FOREIGN KEY (actor_id) REFERENCES public.tb_actor(id);


--
-- Name: tb_movie fko51cku8l99lu7c9g7l9c06tho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_movie
    ADD CONSTRAINT fko51cku8l99lu7c9g7l9c06tho FOREIGN KEY (category_id) REFERENCES public.tb_category(id);


--
-- Name: tb_actor fktg472thvyinx50macm84bij1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_actor
    ADD CONSTRAINT fktg472thvyinx50macm84bij1 FOREIGN KEY (movie_id) REFERENCES public.tb_movie(id);


--
-- PostgreSQL database dump complete
--

